# Generated by Django 5.2.13 on 2026-08-14 12:24

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('core', '0002_tenant_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentItemAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='billing.feestructureitem')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.institution')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.payment')),
            ],
            options={
                'db_table': 'payment_item_allocations',
                'ordering': ('id',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
