# Generated by Django 6.1 on 2026-09-04 15:56

import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_payment_item_allocations_rls'),
        ('core', '0002_tenant_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructureitem',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='StudentFeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_included', models.BooleanField(default=True)),
                ('adjustment_type', models.CharField(default='standard', max_length=20)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.studentfeeassignment')),
                ('fee_structure_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_items', to='billing.feestructureitem')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='core.institution')),
            ],
            options={
                'db_table': 'student_fee_items',
                'ordering': ('id',),
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
