# Generated by Django 6.1 on 2026-08-11 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.institution'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'Owner')), fields=('institution',), name='uniq_owner_per_institution'),
        ),
    ]
