"""
Student forms.

StudentForm is a ModelForm over the biographical fields plus one extra,
non-model field: `klass`. A student's class lives in StudentEnrollment, not on
Student (enrollments are append-only — students/models.py), so the form
collects the class and the view hands it to students.services, which writes the
enrollment row. Keeping `klass` on the form rather than the model is what lets
"add a student" and "assign their class" be one screen without pretending the
class is a column on the student.

The required/optional split docs/03_Views_and_Endpoints.md calls for is declared
once here (REQUIRED_FIELD_NAMES / OPTIONAL_FIELD_NAMES) and read by the template,
so the form and the screen cannot disagree about which fields are which.

There is deliberately no Bursar variant of this form: the permission matrix
gives Bursar no manage access to students, so a Bursar never reaches an edit
form to restrict. Their read-only field restriction is a view-layer context
builder (students/views.py), the other half of docs/04's "restricted ModelForm
*and* a role-aware queryset/context builder".
"""

from django import forms

from academic.models import Class, ClassStatus, Term
from core.forms import AccessibleFormMixin, AccessibleModelForm
from academic.forms import InstitutionScopedFormMixin

from .models import Student


class StudentForm(InstitutionScopedFormMixin, AccessibleModelForm):
    """Add or edit a student, and choose the class to enrol them in.

    `admission_number` is absent on purpose — it is platform-generated by
    students.services at creation, never typed. `photo`, `credit_balance` and
    `status` are absent too: photos are added later (no media pipeline in
    Phase 4), the balance is the payment engine's to move (Phase 5), and status
    changes go through the archive/reactivate buttons so each carries its own
    audit entry.
    """

    # Grouping for the template's required/optional split. `klass` sits in the
    # required group because a student must be enrolled somewhere; middle_name
    # is optional even though it reads alongside the names.
    REQUIRED_FIELD_NAMES = (
        "first_name",
        "last_name",
        "gender",
        "date_of_birth",
        "klass",
        "guardian_name",
        "guardian_phone",
    )
    OPTIONAL_FIELD_NAMES = (
        "middle_name",
        "father_name",
        "mother_name",
        "guardian_email",
        "address",
        "date_of_admission",
    )
    field_order = list(REQUIRED_FIELD_NAMES) + list(OPTIONAL_FIELD_NAMES)

    klass = forms.ModelChoiceField(
        queryset=Class.unscoped.none(),  # narrowed to this institution's active classes in __init__
        label="Class",
        help_text="The class to enrol this student in. Only active classes are listed.",
        error_messages={
            "invalid_choice": (
                "That class isn't available for new enrolments. Choose an active class."
            )
        },
    )

    class Meta:
        model = Student
        fields = (
            "first_name",
            "middle_name",
            "last_name",
            "gender",
            "date_of_birth",
            "father_name",
            "mother_name",
            "guardian_name",
            "guardian_phone",
            "guardian_email",
            "address",
            "date_of_admission",
        )
        labels = {
            "guardian_name": "Guardian name",
            "guardian_phone": "Guardian phone",
            "guardian_email": "Guardian email",
            "father_name": "Father's name",
            "mother_name": "Mother's name",
            "date_of_birth": "Date of birth",
            "date_of_admission": "Date of admission",
        }
        help_texts = {
            "guardian_phone": "Used for payment-related contact.",
            "date_of_admission": "Leave blank if the student hasn't formally started yet.",
        }
        widgets = {
            "date_of_birth": forms.DateInput(attrs={"type": "date"}),
            "date_of_admission": forms.DateInput(attrs={"type": "date"}),
            "address": forms.Textarea(attrs={"rows": 3}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["first_name"].widget.attrs["autofocus"] = True
        # InstitutionScopedFormMixin has already scoped `klass` to this
        # institution's classes (every class, since Class is tenant-scoped);
        # narrow that to active ones, ordered as the school ordered them. Doing
        # it after super().__init__ is deliberate — the mixin runs during it.
        self.fields["klass"].queryset = Class.unscoped.filter(
            institution_id=self.institution_id, status=ClassStatus.ACTIVE
        ).order_by("order", "name")

    def required_fields(self):
        """Bound fields for the 'required' section — see REQUIRED_FIELD_NAMES."""
        return [self[name] for name in self.REQUIRED_FIELD_NAMES]

    def optional_fields(self):
        """Bound fields for the 'optional' section."""
        return [self[name] for name in self.OPTIONAL_FIELD_NAMES]


class BulkImportUploadForm(InstitutionScopedFormMixin, AccessibleFormMixin, forms.Form):
    """Pick the term to enrol into and upload the filled-in template.

    A single term selector rather than separate session + term controls: a term
    already knows its session, so choosing one can't produce a mismatched pair,
    and the view reads `term.session` for the batch. The workbook itself is
    parsed by students.services — this form only confirms it looks like an
    .xlsx before that, so an obviously-wrong file fails with a form error rather
    than reaching the parser.
    """

    term = forms.ModelChoiceField(
        queryset=Term.unscoped.none(),  # scoped in __init__
        label="Enrol these students into",
        help_text="The session and term every student in this file will start in.",
    )
    file = forms.FileField(
        label="Completed template",
        help_text="The .xlsx workbook you downloaded and filled in.",
    )

    field_order = ("term", "file")

    def __init__(self, *args, current_term=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["term"].queryset = (
            Term.unscoped.filter(institution_id=self.institution_id)
            .select_related("session")
            .order_by("-session__start_date", "start_date")
        )
        if current_term is not None and not self.is_bound:
            self.fields["term"].initial = current_term.pk

    def clean_file(self):
        upload = self.cleaned_data["file"]
        if not upload.name.lower().endswith(".xlsx"):
            raise forms.ValidationError(
                "Upload the .xlsx template. Other spreadsheet formats aren't read "
                "in this version — open the file and 'Save As' Excel Workbook (.xlsx) "
                "if you need to convert it."
            )
        return upload
